# Generated by Django 3.2 on 2021-04-17 13:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('day', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], default='MON', max_length=3)),
                ('train_from', models.CharField(max_length=50)),
                ('train_to', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Schedule of Trains',
                'verbose_name_plural': 'Schedules of Trains',
            },
        ),
    ]
